import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import TabContainer from '../components/TabContainer';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <div className={styles['main-inner']}>
          <TabContainer />
        </div>
      </main>
    </div>
  )
}

export default Home;
